FROM osrf/ros:humble-desktop

RUN apt-get update && apt-get install -y \
    ros-humble-turtlesim \
    ros-humble-demo-nodes-cpp \
    neovim ripgrep nano software-properties-common && \
    add-apt-repository -y ppa:zhangsongcui3371/fastfetch && \
    apt-get update && apt-get install -y fastfetch && \
    rm -rf /var/lib/apt/lists/*
RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc
RUN echo "fastfetch" >> /root/.bashrc
WORKDIR /home

COPY . .

